### ISSUE TITLE
Uncaught TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by samstr** [LukeXuan/gulp-watcher#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [gulp-watcher](https://github.com/LukeXuan/gulp-watcher) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'emit' of undefined

```
At /Users/samstr/.atom/packages/gulp-watcher/lib/watcher.coffee:47

TypeError: Cannot read property 'emit' of undefined
  at /Users/samstr/.atom/packages/gulp-watcher/lib/watcher.coffee:47:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at BufferedProcess.module.exports.BufferedProcess.handleError (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:251:20)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:240:24)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:166:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1055:12)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -5:18.9.0 command-palette:toggle (atom-pane.pane.active)
 11x -5:17.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:16.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:16.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:12.3.0 settings-view:open (atom-pane.pane.active)
     -5:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 22x -4:48.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:33.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:35.5.0 gulp-helper:toggle (div.settings-view.pane-item)
     -0:52.8.0 core:cancel (div.pane-item.native-key-bindings.about)
     -0:49 settings-view:open (div.pane-item.native-key-bindings.about)
     -0:00.6.0 gulp-watcher:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
gulp-watcher, v0.1.2
monokai, v0.15.0

# Dev
No dev packages
```

**Comment by LukeXuan** [comment]
I've got some questions.
- Is `gulp` the correct command on the OS X?
- If not, what is it?
